name: CICD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Download project code
        uses: actions/checkout@v4

      - name: Login on Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push of Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            carlosedu13/fake-shop:latest
            carlosedu13/fake-shop:v${{ github.run_number }}
            
  # cd:
  #   runs-on: ubuntu-latest
  #   needs: [ci]
  #   permissions:
  #     id-token: write
  #     contents: read
  #     actions: read
  #   steps:
  #     - name: Download project code
  #       uses: actions/checkout@v4

  #     - name: Login on AWS
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1

  #     - name: Configure kubectl 
  #       run: aws eks update-kubeconfig --name class-k8s

  #     - name: Deploy manifests of Kubernetes
  #       uses: Azure/k8s-deploy@v5
  #       with:
  #          manifests: |
  #             ./k8s/deployment.yaml
  #          images: |
  #             fabricioveronez/fake-shop:v${{ github.run_number }}
